Create cms base structure
openknowledgebe/website pull request #10
Opened 2020-11-16 09:04 UTC by auloin

2020-11-16 09:10 UTC, auloin commented
@jbelien, @MichielLeyman still a draft but I'd appreciate some feedback.

If you'd like to only publish locally run:
`npx netlify-cms-proxy-server`
`gatsby develop`

2020-11-16 13:03 UTC, jbelien commented
Looks good to me 👍 

The preview (right side panel) seems a bit "off" but I guess it needs more config/styling (I don't know Netlify CMS that well).
![Capture d’écran 2020-11-16 à 14 00 10](https://user-images.githubusercontent.com/1150563/99255374-2202d500-2814-11eb-9ba0-2d816449c4b3.png)

Structure seems coherent. I didn't check every page/component but I guess you based the data structure on the "design".

2020-11-16 15:07 UTC, auloin commented
Yes previews need styling, I'll do this later.
Should I allow editors to modify 'static' pages/content through the CMS?

2020-11-16 15:54 UTC, jbelien commented
> Yes previews need styling, I'll do this later.

Okay, thanks 👍 

>  Should I allow editors to modify 'static' pages/content through the CMS?

Yes, I think it will be easier for people that are not used to Git/GitHub to use the CMS to edit the content of static pages.

2020-11-21 09:08 UTC, jbelien requested changes
Great work @auloin 👍 
Some remarks about the structure that could be simplified but this is going really well.

2020-11-21 09:08 UTC, jbelien commented on static/admin/config.yml
> +      - label: 'Navbar'
I would rename it "Header".
Doesn't seem to be used (yet).

I wouldn't put it under "Settings", maybe under something like "UI" where we would have "Header", "Footer", ...

2020-11-21 09:08 UTC, jbelien commented on static/admin/config.yml
> +      - label: 'Footer'
I wouldn't put it under "Settings", maybe under something like "UI" where we would have "Header", "Footer", ...

2020-11-21 09:08 UTC, jbelien commented on src/cms/previews/Post.jsx
> +import React from 'react';
Rename "Post" to "Story" (see other comment in `static/admin/config.yml`)

I have the following error (locally) with the post preview.

![image](https://user-images.githubusercontent.com/1150563/99871949-7b854e00-2bde-11eb-835f-df5b0fa2b64e.png)

2020-11-22 14:58 UTC, auloin commented on static/admin/config.yml
> +media_folder: okbe-website/images/uploads
This is meant to be the folder in which images will be stored. But Cloudinary configurations are still a work in progress, I'll see with Michiel how I can connect with the existing cloud.

2020-11-22 15:05 UTC, auloin commented on static/admin/config.yml
> +    label: 'Activities Overview'
Not splitting would be more confusing I think, I tried one option but got a feedback and discarded it. The only other option left (with the one already in place) would be to put the two collections together and make all the fields of "Activity page" optional. User may decide to not create a page for their activity and just link to an existing website, in this case they only have to create an 'Activity overview'.

2020-11-22 15:08 UTC, auloin commented on static/admin/config.yml
> +    label: 'Posts'
I name it this way because I separated tweet stories from '[blog]post' stories. Is it better to go with 'stories'?

2020-11-22 15:12 UTC, auloin commented on static/admin/config.yml
> +      - label: 'Navbar'
Should I just call it 'Header & Footer'?

2020-11-22 15:19 UTC, auloin commented on src/cms/previews/Post.jsx
> +import React from 'react';
It should work once this branch is merged with `main`  :smile:
Or run `npx netlify-cms-proxy-server` as well as `gatsby develop` to get it to work locally.

2020-11-22 15:57 UTC, jbelien commented on static/admin/config.yml
> +    label: 'Posts'
I would indeed change to stories ; we'll find a solution for the tweets.

2020-11-22 15:57 UTC, jbelien commented on static/admin/config.yml
> +      - label: 'Navbar'
> Should I just call it 'Header & Footer'?

That also works 😄

2020-11-22 15:58 UTC, jbelien commented on src/cms/previews/Post.jsx
> +import React from 'react';
>  Or run `npx netlify-cms-proxy-server` as well as `gatsby develop` to get it to work locally.

That's what I did :)
But good if it works once merged with `main` 👍

2020-11-23 08:42 UTC, auloin commented on src/cms/previews/Post.jsx
> +import React from 'react';
Fixed it! Thank you

2020-11-23 09:16 UTC, jbelien commented on static/admin/config.yml
> +    label: 'Activities Overview'
Okay, let's keep it like this for now.

2020-11-23 09:21 UTC, jbelien commented
Still missing some previews but I'll merge the PR so you can continue  👍

2020-11-23 09:24 UTC, merged