Make all the UI
openknowledgebe/website pull request #13
Opened 2020-11-27 16:46 UTC by auloin

2020-11-27 18:03 UTC, jbelien commented
I'll check it this weekend 👍 
Could you make sure the build is working before I check ?

2020-11-29 11:42 UTC, jbelien requested changes
- [ ] Could you add some "random" content **everywhere** ? For now it's a bit difficult to have an idea what the pages look like and some functionalities in the admin panel doesn't seem to work.
- [ ] Could you disable Cloudinary support during development ?
- [ ] When I try to create a new "Activity Page", the name is a listbox but it's empty (even when I already created an "Activity Overview".

2020-11-29 11:42 UTC, jbelien commented on src/cms/previews/Activity.jsx
> +      <ActivityCard {...data} />
Activity overview logo doesn't appear in the preview.

2020-11-29 11:42 UTC, jbelien commented on src/components/UI/Person.jsx
> +        <Img alt={name} src={picture} />
Picture upload doesn't seem to be available in the admin.

2020-11-29 11:42 UTC, jbelien commented on src/pages/index.js
Could you replace this hardcoded array by "real" activities from the CMS ?
I didn't find the way to pin an activity in the admin panel.

2020-11-29 11:42 UTC, jbelien commented on src/pages/team.js
> +        <Img src={data?.header?.featured_image} alt="" />
Display a box with a black border in the admin preview ... Should be replaced by a placeholder!

2020-11-29 13:22 UTC, auloin commented on src/pages/index.js
I didn't connect the CMS to the homepage, my next task is to connect everything together.
To pin an activity go to `Pages > Home > Activities Section > Featured Activities` , same goes for a story.

2020-11-29 13:25 UTC, auloin commented on src/components/UI/Person.jsx
> +        <Img alt={name} src={picture} />
Correct, this is to be added. I'll have to review all other `image` fields so I plan to add it while doing that.

2020-11-29 13:29 UTC, auloin commented on src/cms/previews/Activity.jsx
> +      <ActivityCard {...data} />
The logo first needs to be uploaded on Cloudinary. The currently in used cloud is one I setup myself, I can switch to okbe one anytime.

2020-11-29 13:40 UTC, auloin commented on src/pages/team.js
> +        <Img src={data?.header?.featured_image} alt="" />
Is this linked to the request to add random content everywhere? Should I make random previews for everything?

2020-11-29 13:44 UTC, jbelien commented on src/cms/previews/Activity.jsx
> +      <ActivityCard {...data} />
Okay, could you completely disable Cloudinary for now then ?

2020-11-29 13:45 UTC, jbelien commented on src/pages/team.js
> +        <Img src={data?.header?.featured_image} alt="" />
No, it's not linked.
For all the previews, I would add a placeholder (like you did for the Person preview).

2020-12-02 15:18 UTC, jbelien commented on static/admin/config.yml
> +        widget: 'datetime'
Since we only need/use the date, why do you go back to the datetime widget (instead of date widget) ?

2020-12-02 15:23 UTC, auloin commented on static/admin/config.yml
> +        widget: 'datetime'
Date is deprecated: [date widget](https://www.netlifycms.org/docs/widgets/#date)

2020-12-02 15:33 UTC, jbelien commented on static/admin/config.yml
> +        widget: 'datetime'
That's indeed ... an EXCELLENT reason.
Sorry :P

2020-12-07 08:35 UTC, merged