Create homepage
openknowledgebe/website pull request #5
Opened 2020-11-06 16:21 UTC by auloin

The website isn't fully responsive but a lot of styling done (```style.css``` is where you'll find most of the interesting stuff).

2020-11-06 21:24 UTC, jbelien commented on src/components/Newsletter.jsx
> +    // console.log(input.current.value);
Try to not commit unnecessary comments.
```suggestion

```

2020-11-06 21:36 UTC, jbelien requested changes
Some remarks:
- Are we sure all browsers are compatibles with TTF font ?
- Could you make sure all files are linted (should be done with `lint-staged`) ?
- `style.css` file is starting to be quite long, could you split it (I personnaly use SASS but you can use whatever you want) ?
- Could you clean unecessary old Gatsy files (`/content/blog`, for instance) ?
- Could you structure the components folders ? Not an issue at the moment but the more components we have, the more "difficult" it will be to find it if all the components are in the same directory.

Also try to work on a branch with a specific name (`homepage` for this PR for instance) so we can delete the branch when the PR is merged.

Thanks!
Good job so far 👍

2020-11-07 17:25 UTC, auloin commented
> * Are we sure all browsers are compatibles with TTF font ?

Support looks good at first glance: [https://caniuse.com/ttf](url)

> * Could you make sure all files are linted (should be done with `lint-staged`) ?

Should be good now (I think only (newly) modified files are checked by lint-staged)

> * `style.css` file is starting to be quite long, could you split it (I personnaly use SASS but you can use whatever you want) ?

This is something I'm thinking about but not sure what's the right way to deal with it: I could work in a component way where every component has its own "stylesheet". How would you like to see me deal with this?

> * Could you clean unecessary old Gatsy files (`/content/blog`, for instance) ?

Done (mostly, I'm keeping some files that may reveal useful).

> * Could you structure the components folders ? Not an issue at the moment but the more components we have, the more "difficult" it will be to find it if all the components are in the same directory.

I'll as soon as I see an opportunity!

2020-11-07 17:31 UTC, jbelien approved these changes

2020-11-07 17:32 UTC, merged

2020-11-07 17:35 UTC, jbelien commented
> This is something I'm thinking about but not sure what's the right way to deal with it: I could work in a component way where every component has its own "stylesheet". How would you like to see me deal with this?

I like the idea (that's how Svelte does it). 👌